import { NextResponse } from 'next/server';
import { readFileSync } from 'fs';
import { join } from 'path';
import { salesAgent, technicalAgent, pricingAgent, orchestratorAgent } from '@/lib/agents';
import { storeProposal } from '@/lib/proposalStore';

export async function POST(request) {
  try {
    const formData = await request.formData();
    const url = formData.get('url');

    if (!url) {
      return NextResponse.json(
        { error: 'No URL provided' },
        { status: 400 }
      );
    }

    // Simulate web scraping by reading local HTML file
    console.log(`🌐 Scanning URL: ${url}`);
    
    let htmlContent;
    try {
      // Extract file path from URL - handle both relative and absolute URLs
      let filePath;
      
      if (url.startsWith('http://') || url.startsWith('https://')) {
        // Parse full URL to extract pathname
        const urlObj = new URL(url);
        filePath = urlObj.pathname;
        // Remove leading slash
        filePath = filePath.startsWith('/') ? filePath.substring(1) : filePath;
        // Remove 'public/' prefix if present in URL
        filePath = filePath.replace(/^public\//, '');
      } else {
        // Handle relative path (e.g., /mock-rfps/portal1.html)
        filePath = url.startsWith('/') ? url.substring(1) : url;
      }
      
      const fullPath = join(process.cwd(), 'public', filePath);
      
      console.log(`📁 Extracted file path: ${filePath}`);
      console.log(`📁 Reading from: ${fullPath}`);
      htmlContent = readFileSync(fullPath, 'utf-8');
    } catch (fileError) {
      console.error('File read error:', fileError);
      return NextResponse.json(
        { error: 'Failed to read portal content. Please check the URL.' },
        { status: 400 }
      );
    }
    
    if (!htmlContent || htmlContent.trim().length === 0) {
      return NextResponse.json(
        { error: 'Portal content is empty or could not be read' },
        { status: 400 }
      );
    }

    console.log(`📊 HTML content size: ${htmlContent.length} characters`);
    
    // Execute agent workflow with HTML content
    console.log('Step 1: Sales Agent analyzing HTML portal...');
    const salesData = await salesAgent(htmlContent);
    
    console.log('Step 2: Technical Agent matches products...');
    // Pass only required products and key requirements (not full RFP text)
    const technicalData = await technicalAgent(
      salesData.requiredProducts, 
      salesData.keyRequirements
    );
    
    console.log('Step 3: Pricing Agent calculates costs...');
    // Pass only essential client and technical data
    const pricingData = await pricingAgent(technicalData, salesData);
    
    console.log('Step 4: Orchestrator synthesizes summary...');
    // Assemble minimal final report data
    const finalReportData = {
      clientInfo: salesData,
      technicalAnalysis: technicalData,
      pricingStrategy: pricingData
    };
    
    const summaryData = await orchestratorAgent(finalReportData);

    // Combine everything into final proposal
    const finalProposal = {
      version: 1,
      changeLog: 'Initial proposal generated by Dhiyanta AI.',
      executiveSummary: summaryData,
      technicalRationale: technicalData,
      pricingStrategy: pricingData,
      clientInfo: {
        client: salesData.client,
        dueDate: salesData.dueDate,
        projectValue: salesData.projectValue,
        keyRequirements: salesData.keyRequirements
      },
      scannedUrl: url,
      originalRFP: htmlContent.substring(0, 5000) // Store excerpt for revision
    };

    // Generate unique ID and store proposal
    const proposalId = Date.now().toString();
    storeProposal(proposalId, finalProposal);

    return NextResponse.json({
      success: true,
      id: proposalId
    });

  } catch (error) {
    console.error('RFP Analysis Error:', error);
    return NextResponse.json(
      { error: error.message || 'Failed to analyze RFP' },
      { status: 500 }
    );
  }
}
